"""Markdown incident report. Defensive actions come from the technique lookup table (no extra LLM call)."""
from sqlalchemy.orm import Session

from .mitre import GENERIC_DEFENSES, TACTIC_DESCRIPTIONS, TECHNIQUES, technique_id
from .models import Incident
from .serializers import incident_ref, iso, linked_incidents

IOC_LABELS = {
    "url": "URL", "phone": "Phone", "email": "Email", "payment_account": "Payment account", "other": "Other",
}


def _cell(value: str) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def _attack_url(tid: str) -> str:
    return "https://attack.mitre.org/techniques/" + tid.replace(".", "/") + "/"


def build_report(db: Session, incident: Incident) -> str:
    profile = incident.profile
    tid = technique_id(profile.mitre_technique)
    technique = TECHNIQUES.get(tid, {})
    links = linked_incidents(db, incident.id)
    ref = incident_ref(incident.id)

    lines = [
        f"# MIRAGE Incident Report — {ref}",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| Status | {incident.status} |",
        f"| Decoy persona | {_cell(incident.persona.name)} — {_cell(incident.persona.role)} |",
        f"| Source | {'Red-Team Simulator: ' + incident.attacker_script.name if incident.attacker_script else 'Manual / real-world input'} |",
        f"| Channel | {incident.channel} |",
        f"| Started | {iso(incident.started_at)} |",
        f"| Closed | {iso(incident.closed_at) or '—'} |",
        f"| Messages | {len(incident.messages)} |",
        f"| Analyzer | {profile.analyzer} (embeddings: {profile.embedding_model}) |",
        "",
        "## Attacker goal",
        "",
        profile.attacker_goal,
        "",
        "## MITRE ATT&CK technique",
        "",
        f"**[{profile.mitre_technique}]({_attack_url(tid)})**" if tid else f"**{profile.mitre_technique}**",
        "",
        technique.get("explanation", ""),
        "",
        "## Indicators of compromise",
        "",
    ]
    if profile.iocs:
        lines += ["| Type | Value |", "|---|---|"]
        lines += [f"| {IOC_LABELS.get(i['type'], i['type'])} | `{_cell(i['value'])}` |" for i in profile.iocs]
    else:
        lines.append("_No indicators were extracted from this conversation._")

    lines += ["", "## Manipulation tactics", ""]
    if profile.manipulation_tactics:
        lines += [f"- **{t}** — {TACTIC_DESCRIPTIONS.get(t, '')}" for t in profile.manipulation_tactics]
    else:
        lines.append("_No manipulation tactics identified._")

    lines += ["", "## Linked incidents", ""]
    if links:
        lines += [
            "These incidents have profile embeddings above the similarity threshold and are likely the same "
            "attacker or campaign.",
            "",
            "| Incident | Similarity | Persona | Technique | Goal |",
            "|---|---|---|---|---|",
        ]
        lines += [
            f"| {link['ref']} | {link['similarity'] * 100:.1f}% | {_cell(link['persona_name'])} | "
            f"{_cell(link['mitre_technique'] or '—')} | {_cell(link['attacker_goal'] or '—')} |"
            for link in links
        ]
    else:
        lines.append("_No similar past incidents found._")

    actions = list(technique.get("defenses", []))[:3]
    if links:
        actions.append(
            f"Treat {ref} and {', '.join(link['ref'] for link in links)} as one campaign: correlate IOCs, "
            "block shared infrastructure together, and brief all targeted teams."
        )
    if len(actions) < 2:
        actions += GENERIC_DEFENSES
    lines += ["", "## Recommended defensive actions", ""]
    lines += [f"{n}. {action}" for n, action in enumerate(actions, 1)]

    lines += ["", "## Transcript", ""]
    for m in incident.messages:
        speaker = "Attacker" if m.sender == "attacker" else f"Decoy ({incident.persona.name.split()[0]})"
        lines.append(f"> **{speaker}:** {m.content}")
        lines.append(">")
    if lines[-1] == ">":
        lines.pop()
    lines += ["", "---", "_Generated by MIRAGE. All persona responses were produced by a decoy; no real data was disclosed._", ""]
    return "\n".join(lines)
